server:
  port: ${ITLAB_NOTIFY_PORT:8080}

spring:
  application:
    name: Notify-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      jdbc:
        time_zone: ${ITLAB_NOTIFY_TZ:Europe/Moscow}
      ddl-auto: ${ITLAB_NOTIFY_SCHEME_POLICY:update}
  datasource:
    url: jdbc:postgresql://${ITLAB_NOTIFY_DB_HOST:localhost}:${ITLAB_NOTIFY_DB_PORT:5432}/${ITLAB_NOTIFY_DB_NAME:notify}
    username: ${ITLAB_NOTIFY_DB_USER:postgres}
    password: ${ITLAB_NOTIFY_DB_PASS:0000}

database:
  redis:
    host: ${ITLAB_NOTIFY_REDIS_HOST:localhost}
    port: ${ITLAB_NOTIFY_REDIS_PORT:6379}
    password: ${ITLAB_NOTIFY_REDIS_PASSWORD:admin}
    channels: reports,events,comments,feedback,pushInfo
    sendChannel: ${ITLAB_NOTIFY_PUSH_CHANNEL:pushInfo}

secrets:
  url: ${ITLAB_NOTIFY_AUTH_URL:https://dev.manage.rtuitlab.dev/api/user/all}
  token: ${ITLAB_NOTIFY_AUTH_TOKEN}
  queryAll: ${ITLAB_NOTIFY_AUTH_GET_QUERY_ALL:?count=-1&offset=0}
  queryFeedbackAdmins: ${ITLAB_NOTIFY_AUTH_GET_QUERY_FEEDBACKADMINS:?claimType=itlab&claimValue=feedback.admin}